### PR TITLE
Add dockerfile + docker instructions

### PR DESCRIPTION
**Pull request by pierce-smith1**
Add a Dockerfile and a set of instructions to the main README.md for building and running it.

### CODE REVIEW

**Comment by drg101** [comment]
Should there be any output after running the `docker run` command?

**Comment by pierce-smith1** [comment]
I would like to figure out why it doesn't seem to log anything to stdout, but it is still completely functional - you just have to run it in something like tmux, or with the `--detach` flag to put it in the background.

**Comment by drg101** [comment]
Yeah it works, the only thing I see is that `docker build --t watercolor .` doesn't work, I think it should be `-t`?

**Comment by drg101** [comment]
Thanks for getting this set up btw!

**Comment by pierce-smith1** [comment]
You're right, it should be `-t` and not `--t`. Whoops.

**Review by drg101 — APPROVED** [review]

**Pull request merged**
